version: '3.3'

services:

  mongo:
    image: mongo:5.0.7
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

  cassandra:
    image: jesusbc/cassandra:latest
    container_name: cassandra
    volumes:
      - cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"

  tfm-front-end:
    image: jesusbc/tfm-front-end:latest
    container_name: tfm-front-end
    ports:
      - "4200:4200"
    env_file:
      - env_vars.env

  plots:
    image: jesusbc/plots:latest
    container_name: plots
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - env_vars.env

  sensor:
    image: jesusbc/sensor:latest
    container_name: sensor
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    env_file:
      - env_vars.env

  authentication:
    image: jesusbc/authentication:latest
    container_name: authentication
    ports:
      - "8999:8999"
    depends_on:
      - mysql
    env_file:
      - env_vars.env

  statistics:
    image: jesusbc/statistics:latest
    container_name: statistics
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - cassandra
    env_file:
      - env_vars.env

volumes:
  postgres_data:
  mysql_data:
  mongo_data:
  cassandra_data:
